version: '3'

services:
  database:
    image: mariadb:10.9.3
    restart: always
    command:
      [
        'mysqld',
        '--character-set-server=utf8',
        '--collation-server=utf8_unicode_ci',
        '--default-time-zone=+00:00',
      ]
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: '+00:00'
    ports:
      - '3306:3306'
    volumes:
      - './data/db:/var/lib/mysql'
